// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVtPz1H6SfaxTg3JjraSP0v1O7vsiVHRQ',
    appId: '1:319721210297:android:76da8c9f2cf3bf4eb6b668',
    messagingSenderId: '319721210297',
    projectId: 'evertec-project',
    storageBucket: 'evertec-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2eI3dAks1bGekrDX0i3mAFe2nccLqn64',
    appId: '1:319721210297:ios:a7550a7627ed5bdfb6b668',
    messagingSenderId: '319721210297',
    projectId: 'evertec-project',
    storageBucket: 'evertec-project.firebasestorage.app',
    androidClientId: '319721210297-60ktptuka2uqp1rkeq8jaaaqh143d58i.apps.googleusercontent.com',
    iosClientId: '319721210297-dhu6189ip3h2ga35tbrm9mvmr3o945rr.apps.googleusercontent.com',
    iosBundleId: 'com.example.evertecTechnicalTest',
  );

}